name: "Purge obsolete draft"

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: curl
          uses: enflo/curl-action@master
          with:
            curl: ${{ secrets.CURL_ARGUMENTS }}
